
package bank.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankServiceImplService", targetNamespace = "http://soap.bank/", wsdlLocation = "http://localhost:9876/hs?wsdl")
public class BankServiceImplService
    extends Service
{

    private final static URL BANKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BANKSERVICEIMPLSERVICE_QNAME = new QName("http://soap.bank/", "BankServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9876/hs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BANKSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BankServiceImplService() {
        super(__getWsdlLocation(), BANKSERVICEIMPLSERVICE_QNAME);
    }

    public BankServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKSERVICEIMPLSERVICE_QNAME, features);
    }

    public BankServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BANKSERVICEIMPLSERVICE_QNAME);
    }

    public BankServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKSERVICEIMPLSERVICE_QNAME, features);
    }

    public BankServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankServiceImpl
     */
    @WebEndpoint(name = "BankServiceImplPort")
    public BankServiceImpl getBankServiceImplPort() {
        return super.getPort(new QName("http://soap.bank/", "BankServiceImplPort"), BankServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankServiceImpl
     */
    @WebEndpoint(name = "BankServiceImplPort")
    public BankServiceImpl getBankServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.bank/", "BankServiceImplPort"), BankServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BANKSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BANKSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
